
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MARGARET THATHER
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class StudentDBGUI extends javax.swing.JFrame {

    Connection cn;
    PreparedStatement pst;
    ResultSet rs;
    
    
    
    public StudentDBGUI() {
        initComponents();
        myconnection();
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        idnumber = new javax.swing.JTextField();
        major = new javax.swing.JTextField();
        fees = new javax.swing.JTextField();
        submitdata = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        firstrecord1 = new javax.swing.JButton();
        lastrecord = new javax.swing.JButton();
        nextrecord = new javax.swing.JButton();
        previousrecords = new javax.swing.JButton();
        displayall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("STUDENT INFORMATION");

        jLabel2.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Lastname");

        jLabel4.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("Id_number");

        jLabel6.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Major");

        jLabel7.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Fees");

        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        submitdata.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        submitdata.setText("Submit Data");
        submitdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitdataActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        clear.setText("Clear");

        firstrecord1.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        firstrecord1.setText("First record");
        firstrecord1.setBorder(null);
        firstrecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstrecord1ActionPerformed(evt);
            }
        });

        lastrecord.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        lastrecord.setText("Lastrecord");
        lastrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastrecordActionPerformed(evt);
            }
        });

        nextrecord.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        nextrecord.setText("nextrecord");
        nextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextrecordActionPerformed(evt);
            }
        });

        previousrecords.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        previousrecords.setText("previousrecords");
        previousrecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousrecordsActionPerformed(evt);
            }
        });

        displayall.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        displayall.setText("displayall");
        displayall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitdata, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nextrecord))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(previousrecords)
                                        .addGap(57, 57, 57)
                                        .addComponent(displayall))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(clear)
                                        .addGap(18, 18, 18)
                                        .addComponent(firstrecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lastrecord)))))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(major, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitdata)
                    .addComponent(clear)
                    .addComponent(firstrecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastrecord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextrecord)
                    .addComponent(previousrecords)
                    .addComponent(displayall))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void submitdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitdataActionPerformed
        // TODO add your handling code here:
        submitrecords() ;
    }//GEN-LAST:event_submitdataActionPerformed

    private void firstrecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrecord1ActionPerformed
        // TODO add your handling code here:
        firstrecord();
    }//GEN-LAST:event_firstrecord1ActionPerformed

    private void lastrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastrecordActionPerformed
        // TODO add your handling code here:
        lastrecord();
    }//GEN-LAST:event_lastrecordActionPerformed

    private void nextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextrecordActionPerformed
        // TODO add your handling code here:
        nextrecord();
    }//GEN-LAST:event_nextrecordActionPerformed

    private void previousrecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousrecordsActionPerformed
        // TODO add your handling code here:
        previousrecords();
    }//GEN-LAST:event_previousrecordsActionPerformed

    private void displayallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayallActionPerformed
        // TODO add your handling code here:
        displayall();
    }//GEN-LAST:event_displayallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDBGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton displayall;
    private javax.swing.JTextField fees;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton firstrecord1;
    private javax.swing.JTextField gender;
    private javax.swing.JTextField idnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastname;
    private javax.swing.JButton lastrecord;
    private javax.swing.JTextField major;
    private javax.swing.JButton nextrecord;
    private javax.swing.JButton previousrecords;
    private javax.swing.JButton submitdata;
    // End of variables declaration//GEN-END:variables

    private void myconnection() {
        try{
            cn=DriverManager.getConnection("jdbc:mysql://localhost/usiustudent", "root", null);
            rs = cn.prepareStatement("SELECT * FROM studentinfo", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY).executeQuery();
            JOptionPane.showMessageDialog(null, "connected successfully");
        }
        catch(Exception e){
            System.out.print(e);
            //e.printStackTrace();
        }
    }

    private void submitrecords() {
        try {
            pst=cn.prepareStatement("INSERT INTO STUDENTINFO VALUES(?, ?, ?, ?, ?, ?)");
            pst.setString(1, firstname.getText());
            pst.setString(2, lastname.getText());
            pst.setString(3, gender.getText());
            pst.setString(4, idnumber.getText());
            pst.setString(5, major.getText());
            pst.setString(6, fees.getText()); //surround and throw execute
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Message Succesfully Saved");
            getclear();
        } catch (Exception e) {
            e.printStackTrace();
           
        }
    }

    private void getclear() {
        firstname.setText( null);
        lastname.setText( null);
        gender.setText( null);
        idnumber.setText( null);
        major.setText( null);
        fees.setText( null);
        
    }
    
    private void firstrecord(){
        
        try {
rs.first();
System.out.println(rs.getString(1)+"\t"+
rs.getString(2)+"\t"+
rs.getString(3)+"\t"+
rs.getString(4)+"\t"+
rs.getString(5)+"\t"+
rs.getString(6));
        } catch (SQLException ex) {
            Logger.getLogger(StudentDBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        }
        
        //surround with try and catch
        //ex.PrintStackTrace

    private void lastrecord(){
        try {
            rs.last();
            System.out.println(rs.getString(1)+"\t"+
                    rs.getString(2)+"\t"+
                    rs.getString(3)+"\t"+
                    rs.getString(4)+"\t"+
                    rs.getString(5)+"\t");
        } catch (SQLException ex) {
            Logger.getLogger(StudentDBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void nextrecord() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        try{
            if(rs.next()==true){
                System.out.println(rs.getString(1)+"\t"+
                rs.getString(2)+"\t"+
                rs.getString(3)+"\t"+
                rs.getString(4)+"\t"+
                rs.getString(5)+"\t");
            }else {
            rs.beforeFirst(); // Move cursor to the position before the first row
        }
    } catch (SQLException ex) {
        Logger.getLogger(StudentDBGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
            
    
}

    private void previousrecords() {
        try {
            //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            
            if (rs.previous()==true) {
                System.out.println(rs.getString(1)+"\t"+
                        rs.getString(2)+"\t"+
                        rs.getString(3)+"\t"+
                        rs.getString(4)+"\t"+
                        rs.getString(5)+"\t");
            } else {
                rs.beforeFirst();
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentDBGUI.class.getName()).log(Level.SEVERE, null, ex);
}
    }
        
    private void displayall(){
        try {
            myconnection();
            
            while (rs.next()==true){
                System.out.println(rs.getString(1)+"\t"+
                        rs.getString(2)+"\t"+
                        rs.getString(3)+"\t"+
                        rs.getString(4)+"\t"+
                        rs.getString(5)+"\t");
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentDBGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
                
    

    



